# Generated by Django 5.1.4 on 2025-01-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
